### ISSUE TITLE
Database changes

### ISSUE THREAD

**Issue by rinkuvatscs** [aviral-92/ac-service#2]
Change Tables names --

ac_type  to CMT_TYPE-- acId to cmtId
customer_repairing_detail to customer_job_detail

And your 
ALTER TABLE `customer_mgmt_tool`.`user_detail_history` 
ADD CONSTRAINT `Foreign_Key_Username`
  FOREIGN KEY (`username`)
  REFERENCES `customer_mgmt_tool`.`login` (`username`)
  ON DELETE CASCADE
  ON UPDATE NO ACTION;

this query not working in Mysql using cmd

**Comment by aviral-92** [comment]
![capture](https://cloud.githubusercontent.com/assets/17472010/16707782/83f7eb7c-45f8-11e6-842c-8b959cdca10c.PNG)
in mine it is working

**Comment by rinkuvatscs** [comment]
Done . closing it
