### ISSUE TITLE
UserDetails module olmost complete bt need ur hlp

### ISSUE THREAD

**Issue by aviral-92** [aviral-92/ac-service#3]
Hi @rinkuvatscs ,
User part is completed almost, validation is left.
please review my code, thoda khich peech sa ho gya h. m sai ni kr para or na hi usski quality sai kr para i knw kafi khrab h so aap review kr k muje bta do sai m khud hi krunga taki quality check muje b aa jye.

one more thing update krte samay user ki details me if phle se same mobile no. ya email pda ho to vo b check krna padega, m usse check ni kr para ki kis trah se krun. i knw vaise to aapko bht hi kuch change krne ka material mil jyga bt still let me know DAO part me kya sai krun.

**Comment by rinkuvatscs** [comment]
Thanks for info Aviral , I will surly check and update for the same .

**Comment by rinkuvatscs** [comment]
Done closing it
