### ISSUE TITLE
Need to sql query. i want to update one of my column while joining 3 tables. i search on net but didnt able to execute it.

### ISSUE THREAD

**Issue by aviral-92** [aviral-92/ac-service#6]
Hi @rinkuvatscs ,

Need to sql query. i want to update one of my column while joining 3 tables. i search on net but didnt able to execute it.

1) http://stackoverflow.com/questions/15209414/how-to-do-3-table-join-in-update-query
2) http://dba.stackexchange.com/questions/21152/how-to-update-one-table-based-on-another-tables-values-on-the-fly/36664

**Comment by rinkuvatscs** [comment]
I will check please come on team viewer

**Comment by rinkuvatscs** [comment]
Aviral , I have resolved this issue so no need to do like that so i am closing it
